import 'package:watchball/models/football_match.dart';
import 'package:icons_plus/icons_plus.dart';

List<FootballMatch> liveMatches = [
  FootballMatch(
      teamOneIcon: Flags.england,
      teamOneName: "England",
      teamOneScore: 5,
      teamOneOdds: 4.4,
      teamTwoIcon: Flags.germany,
      teamTwoName: "Germany",
      teamTwoScore: 3,
      teamTwoOdds: 3.6,
      drawOdds: 5.0,
      gameTime: 0,
      dateTime: DateTime.now(),
      competition: "Premier League",
      stage: "Semi Final",
      host: "England"),
  FootballMatch(
      teamOneIcon: Flags.nigeria,
      teamOneName: "Nigeria",
      teamOneScore: 3,
      teamOneOdds: 2.3,
      teamTwoIcon: Flags.egypt,
      teamTwoName: "Egypt",
      teamTwoScore: 0,
      teamTwoOdds: 3.7,
      drawOdds: 2.0,
      gameTime: 5400,
      dateTime: DateTime.now(),
      competition: "Premier League",
      stage: "Semi Final",
      host: "England"),
  FootballMatch(
      teamOneIcon: Flags.argentina,
      teamOneName: "Argentina",
      teamOneScore: 3,
      teamOneOdds: 4.3,
      teamTwoIcon: Flags.brazil,
      teamTwoName: "Brazil",
      teamTwoScore: 0,
      teamTwoOdds: 4.7,
      drawOdds: 1.0,
      gameTime: 500,
      dateTime: DateTime.now(),
      competition: "Premier League",
      stage: "Semi Final",
      host: "England"),
  FootballMatch(
      teamOneIcon: Flags.argentina,
      teamOneName: "Argentina",
      teamOneScore: 3,
      teamOneOdds: 4.3,
      teamTwoIcon: Flags.brazil,
      teamTwoName: "Brazil",
      teamTwoScore: 0,
      teamTwoOdds: 4.7,
      drawOdds: 1.0,
      gameTime: 500,
      dateTime: DateTime.now(),
      competition: "Premier League",
      stage: "Semi Final",
      host: "England"),
  FootballMatch(
      teamOneIcon: Flags.argentina,
      teamOneName: "Argentina",
      teamOneScore: 3,
      teamOneOdds: 4.3,
      teamTwoIcon: Flags.brazil,
      teamTwoName: "Brazil",
      teamTwoScore: 0,
      teamTwoOdds: 4.7,
      drawOdds: 1.0,
      gameTime: 500,
      dateTime: DateTime.now(),
      competition: "Premier League",
      stage: "Semi Final",
      host: "England"),
];
