// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-Az20TexUWnPtmtflgJxQ029dlTaR_k',
    appId: '1:1046259746616:web:8f63a2dabb324b4f9de3cd',
    messagingSenderId: '1046259746616',
    projectId: 'watchball',
    authDomain: 'watchball.firebaseapp.com',
    storageBucket: 'watchball.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg2wrotOai0OmdSrAsNGBAs7pMmWLBSvM',
    appId: '1:1046259746616:android:dafa99c97d61e9289de3cd',
    messagingSenderId: '1046259746616',
    projectId: 'watchball',
    storageBucket: 'watchball.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXB5BwPP1U2LB5CZ9tV792eSPCwOLdlrg',
    appId: '1:1046259746616:ios:48f894a55955d1919de3cd',
    messagingSenderId: '1046259746616',
    projectId: 'watchball',
    storageBucket: 'watchball.appspot.com',
    iosBundleId: 'com.hms.watchball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXB5BwPP1U2LB5CZ9tV792eSPCwOLdlrg',
    appId: '1:1046259746616:ios:48f894a55955d1919de3cd',
    messagingSenderId: '1046259746616',
    projectId: 'watchball',
    storageBucket: 'watchball.appspot.com',
    iosBundleId: 'com.hms.watchball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO-Az20TexUWnPtmtflgJxQ029dlTaR_k',
    appId: '1:1046259746616:web:688b33ef558a20f79de3cd',
    messagingSenderId: '1046259746616',
    projectId: 'watchball',
    authDomain: 'watchball.firebaseapp.com',
    storageBucket: 'watchball.appspot.com',
  );

}